### ISSUE TITLE
Please add Hour and minute to format function.

### ISSUE THREAD

**Issue by miladr** [opilo/farsi#3]

**Comment by halaei** [comment]
check out master (no tag yet). A new class JDateTime is added. For example:

``` php
echo(JDateTime::fromDateTime(new DateTime())->format('Y/m/d H:i')));
```

will output

```
۱۳۹۵/۰۳/۰۲ ۰۷:۲۸
```

Is that what you mean?

**Comment by miladr** [comment]
exactly. Is master stable enough?

**Comment by halaei** [comment]
I have tested it, but not yet personally used. I guess @ahmadbadpey has tried it. [This](https://github.com/halaei/jalali/issues/2) is his issue in another package that leads to the changes here in master.

I will tag it soon to 1.0.0

**Comment by miladr** [comment]
Very well. I will test it and let you know if anything went wrong. Thank you :100:

**Comment by halaei** [comment]
Your welcome buddy.
