### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bahman2216** [opilo/farsi#4]
Hi
There is no installation method ?
**JalaliServiceProvider** not found in package.

**Comment by Anisi** [comment]
Hello
That's right, I think it's renamed and it is not updated in the document.
Replacing `JalaliServiceProvider` with `FarsiServiceProvider` solved the problem.

**Comment by halaei** [comment]
Thanks. It was a readme bug and is now fixed. Use `FarsiServiceProvider` instead.
